# Generated by Django 3.0.6 on 2020-07-18 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='DateInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(verbose_name='Published date')),
                ('updated_at', models.DateTimeField(verbose_name='Last updated')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('dateinformation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blogs.DateInformation')),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Author')),
            ],
            bases=('blogs.dateinformation',),
        ),
    ]
