# Generated by Django 3.0.6 on 2020-07-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateinformation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dateinformation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
